#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PANDOC_BIN="${PANDOC:-pandoc}"
PDF_ENGINE_BIN="${PDF_ENGINE:-xelatex}"
PY_BIN="${PYTHON:-python}"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/build_book_ch00_06_with_labs_and_solutions.sh [OUT.pdf]
  ./scripts/build_book_ch00_06_with_labs_and_solutions.sh --format pdf [--output OUT.pdf]
  ./scripts/build_book_ch00_06_with_labs_and_solutions.sh --format tex [--output OUT.tex]
  ./scripts/build_book_ch00_06_with_labs_and_solutions.sh --format md  [--output OUT.md]

Defaults:
  pdf -> docs/book/compiled/book_ch00-06_with_labs_and_solutions.pdf
  tex -> docs/book/compiled/book_ch00-06_with_labs_and_solutions.tex
  md  -> docs/book/compiled/book_ch00-06_with_labs_and_solutions.md
EOF
}

FORMAT=""
OUT_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --format)
      FORMAT="${2:-}"
      shift 2
      ;;
    -o|--output)
      OUT_FILE="${2:-}"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      # Backward-compatible positional output file (PDF by default).
      OUT_FILE="$1"
      shift
      ;;
  esac
done

if [[ -z "$FORMAT" ]]; then
  case "$OUT_FILE" in
    *.tex) FORMAT="tex" ;;
    *.md) FORMAT="md" ;;
    *) FORMAT="pdf" ;;
  esac
fi

if [[ -z "$OUT_FILE" ]]; then
  case "$FORMAT" in
    pdf) OUT_FILE="docs/book/compiled/book_ch00-06_with_labs_and_solutions.pdf" ;;
    tex) OUT_FILE="docs/book/compiled/book_ch00-06_with_labs_and_solutions.tex" ;;
    md) OUT_FILE="docs/book/compiled/book_ch00-06_with_labs_and_solutions.md" ;;
    *)
      echo "Unknown --format: $FORMAT (expected: pdf|tex|md)" >&2
      usage >&2
      exit 2
      ;;
  esac
fi

OUT_LOG=""
case "$FORMAT" in
  pdf) OUT_LOG="${OUT_FILE%.pdf}.log" ;;
  tex) OUT_LOG="${OUT_FILE%.tex}.tex.log" ;;
  md) OUT_LOG="${OUT_FILE%.md}.md.log" ;;
esac

mkdir -p "$(dirname "$OUT_FILE")"
mkdir -p "$(dirname "$OUT_LOG")"

SOURCES=(
  docs/book/ch00/ch00_motivation_first_experiment.md
  docs/book/ch00/exercises_labs.md
  docs/book/ch00/ch00_lab_solutions.md
  docs/book/ch01/ch01_foundations.md
  docs/book/ch01/exercises_labs.md
  docs/book/ch01/ch01_lab_solutions.md
  docs/book/ch02/ch02_probability_measure_click_models.md
  docs/book/ch02/exercises_labs.md
  docs/book/ch02/ch02_lab_solutions.md
  docs/book/ch03/ch03_stochastic_processes_bellman_foundations.md
  docs/book/ch03/exercises_labs.md
  docs/book/ch03/ch03_lab_solutions.md
  docs/book/ch04/ch04_generative_world_design.md
  docs/book/ch04/exercises_labs.md
  docs/book/ch05/ch05_relevance_features_reward.md
  docs/book/ch05/exercises_labs.md
  docs/book/ch06/discrete_template_bandits.md
  docs/book/ch06/exercises_labs.md
  docs/book/ch06/ch06_lab_solutions.md
  docs/book/ch06/ch06_advanced_gpu_lab.md
)

for f in "${SOURCES[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "Missing source file: $f" >&2
    exit 2
  fi
done

TMP_DIR="$(mktemp -d)"
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

echo "[sanitize] Writing sanitized markdown to: $TMP_DIR" >&2
"$PY_BIN" scripts/sanitize_markdown_for_latex.py --output-dir "$TMP_DIR" "${SOURCES[@]}"

SANITIZED_SOURCES=()
for f in "${SOURCES[@]}"; do
  SANITIZED_SOURCES+=("$TMP_DIR/$f")
done

RESOURCE_PATH=".:docs/book"
for ch in ch00 ch01 ch02 ch03 ch04 ch05 ch06; do
  RESOURCE_PATH="$RESOURCE_PATH:docs/book/$ch"
done

BOOK_TITLE="Reinforcement Learning for Search from Scratch (Chapters 0--6)"
BOOK_AUTHOR="Vlad Prytula"

if [[ "$FORMAT" == "md" ]]; then
  echo "[md] Writing combined markdown: $OUT_FILE" >&2
  : >"$OUT_FILE"
  cat >>"$OUT_FILE" <<EOF
---
title: "$BOOK_TITLE"
author: "$BOOK_AUTHOR"
---

<!-- AUTOGENERATED: combined from docs/book/ch00..ch06 (incl. labs + available solutions) -->

EOF
  for f in "${SANITIZED_SOURCES[@]}"; do
    cat "$f" >>"$OUT_FILE"
    printf "\n\n" >>"$OUT_FILE"
  done
  if rg -nP "[^\\x00-\\x7F]" "$OUT_FILE" >/dev/null; then
    echo "[error] Non-ASCII characters found in: $OUT_FILE" >&2
    exit 1
  fi
  echo "[done] $OUT_FILE" >&2
  exit 0
fi

if [[ "$FORMAT" == "tex" ]]; then
  echo "[pandoc] Building LaTeX: $OUT_FILE" >&2
  "$PANDOC_BIN" \
    "${SANITIZED_SOURCES[@]}" \
    --from=markdown+tex_math_dollars+tex_math_single_backslash+raw_html+fenced_divs \
    --to=latex \
    --standalone \
    --lua-filter=docs/book/admonitions.lua \
    --lua-filter=docs/book/callouts.lua \
    --lua-filter=docs/book/crossrefs.lua \
    --include-in-header=docs/book/preamble.tex \
    --resource-path="$RESOURCE_PATH" \
    --syntax-highlighting=tango \
    -V documentclass=article \
    -V geometry:margin=1in \
    -V fontsize=11pt \
    --toc --toc-depth=2 \
    --metadata title="$BOOK_TITLE" \
    --metadata author="$BOOK_AUTHOR" \
    -o "$OUT_FILE" \
    2>&1 | tee "$OUT_LOG"

  if rg -nP "[^\\x00-\\x7F]" "$OUT_FILE" >/dev/null; then
    echo "[error] Non-ASCII characters found in: $OUT_FILE" >&2
    exit 1
  fi
  echo "[done] $OUT_FILE" >&2
  echo "[done] $OUT_LOG" >&2
  exit 0
fi

echo "[pandoc] Building PDF: $OUT_FILE" >&2
"$PANDOC_BIN" \
  "${SANITIZED_SOURCES[@]}" \
  --from=markdown+tex_math_dollars+tex_math_single_backslash+raw_html+fenced_divs \
  --lua-filter=docs/book/admonitions.lua \
  --lua-filter=docs/book/callouts.lua \
  --lua-filter=docs/book/crossrefs.lua \
  --include-in-header=docs/book/preamble.tex \
  --pdf-engine="$PDF_ENGINE_BIN" \
  --resource-path="$RESOURCE_PATH" \
  --syntax-highlighting=tango \
  -V geometry:margin=1in \
  -V fontsize=11pt \
  --toc --toc-depth=2 \
  --metadata title="$BOOK_TITLE" \
  --metadata author="$BOOK_AUTHOR" \
  -o "$OUT_FILE" \
  2>&1 | tee "$OUT_LOG"

if rg -n --no-filename -i "missing character|invalid input character|Unicode" "$OUT_LOG" >/dev/null; then
  echo "" >&2
  echo "[error] LaTeX log contains missing/Unicode character warnings. See: $OUT_LOG" >&2
  exit 1
fi

echo "[done] $OUT_FILE" >&2
echo "[done] $OUT_LOG" >&2
